@startuml


rectangle consumer
rectangle provider
rectangle zookeeper
rectangle dubboAdmin

consumer -up-> zookeeper :监听消费
provider -up-> zookeeper :注册

consumer -> provider :远程调用

dubboAdmin -do-> zookeeper :监听





@enduml